### ISSUE TITLE
Color of badges.

### ISSUE THREAD

**Issue by loconluis** [Yummygum/city-lights-syntax-vsc#1]
It is possible to change the color of the badges that notify how many files have changed in git. It is a bit dark.
![captura de 2017-11-05 00 28 34](https://user-images.githubusercontent.com/12422912/32412538-47d2ca28-c1c0-11e7-9fcf-6b3d53ab86bb.png)

**Comment by 4ern** [comment]
@loconluis you can add this in your settings.json 

```
"workbench.colorCustomizations": {
    "activityBarBadge.background": "#5EC4FF"
},

**Comment by noudadrichem** [comment]
@loconluis Thanks for the feedback! I'll edit this soon, i'll let you know when I patched it.
