### ISSUE TITLE
Go to definition popup hard to read.

### ISSUE THREAD

**Issue by bdielman** [Yummygum/city-lights-syntax-vsc#15]
Loving the theme. Only issue I've noticed so far is that the go to definition pop is hard to read with the light text on the light blue background.

<img width="194" alt="screen shot 2018-02-22 at 10 38 32 pm" src="https://user-images.githubusercontent.com/94547/36576908-cd13d684-1821-11e8-93d3-ca9fc4f7c46f.png">

**Comment by noudadrichem** [comment]
Hi @bdielman,

I'll fix this bug soon, more and more issues with weird tooltips popping up. Thanks for reporting! 

Sincerely

**Comment by ashtonlance** [comment]
Any updates here?

**Comment by noudadrichem** [comment]
Did you update? @ashtonlance

**Comment by ashtonlance** [comment]
Yep, I'm using 1.0.4. Still seeing the same as the screencap posted above.

**Comment by ashtonlance** [comment]
Awesome thanks!

**Comment by noudadrichem** [comment]
This should work properly now, let me know if other things you don't expect occur!
