### ISSUE TITLE
Vim version

### ISSUE THREAD

**Issue by AndresRodH** [Yummygum/city-lights-syntax-vsc#16]
I ❤️ this theme. I don't know if here is the place for this sort of request, but it would be great if there was a vim colorscheme of City Lights!

**Comment by noudadrichem** [comment]
Hi @AndresRodH,

Glad you like the theme! I'm not so familiar with VIM myself, I tried to use http://coloration.sickill.net/ to convert the .tmTheme file to VIM but this only redirects to weird URIs. Maybe you could try it on your machine. 😊
You can find the .tmTheme in the sublime repo.

Sincerely

**Comment by AndresRodH** [comment]
Thanks! I'll try that for sure 😃

**Comment by noudadrichem** [comment]
Let me know if it worked!

**Comment by AndresRodH** [comment]
With the link you gave me I was able to pin down the source. The github repo is https://github.com/sickill/coloration and I used tm2vim to generate the .vim file.

This is the result. It is so very close!
![screen shot 2018-03-21 at 1 59 44 pm](https://user-images.githubusercontent.com/16929001/37731462-22e7496c-2d10-11e8-91f1-8e6e856068ca.png)

**Comment by noudadrichem** [comment]
Wieww awesome! Enjoy it!

**Comment by noudadrichem** [comment]
I got this.. auchh.. Did you do anything special to make it work like in the above screen you send? It looks awesome 😊

![image](https://user-images.githubusercontent.com/16288476/37759549-3cb0f9ac-2db4-11e8-96f1-bf49e527b887.png)

**Comment by AndresRodH** [comment]
Oh! It might be that your terminal does not support 24-bit color. Run this in your shell `printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"`
If it NOT display the word TRUECOLOR in red, it does not support 24-bit color. I am using iTerm2 which does support it and in my `.vimrc` file I have:
 ```
  if (has("termguicolors"))
    set termguicolors
  endif
```
This works for Neovim > 0.1.5 and Vim > patch 7.4.1799. Let me know if this worked! I don't think I have anything else on my `.vimrc` that does anything to colors in general.

**Comment by noudadrichem** [comment]
Did some research and you're right, Apple's default terminal does not support 24-bit colors.. Sad with all those amazing screens they're releasing now on their machines. Thank you for the help!

Sincerely

**Comment by nermolov** [comment]
@noudadrichem you should try out iterm2! it supports 24 bit color

**Comment by nermolov** [comment]
@noudadrichem you can try setting your TERM env variable to `xterm-256color` or if that doesn't work adding `set t_Co=256` to your vimrc might help

**Comment by noudadrichem** [comment]
Thanks for the tip! @nermolov 

I added `set t_Co=256` to my `.vimrc`. But this still happens: http://jmp.sh/sUgWnxV
It also says it can't find the City Lights theme, which is strange because it is in my `.vim/colors` directory

**Comment by saltdotac** [comment]
Wanted to shamelessly self promote my conversion here https://github.com/saltdotac/citylights.vim/blob/master/colors/citylights.vim

Still working on it but if you're using termguicolors it's progressing quickly.

**Comment by noudadrichem** [comment]
Nice plug! haha. Gonna try that out! I got this working just fine as well! 
_My vim version:_
https://gist.github.com/noudadrichem/47ec84f511fd2e2334cf3f299f99e352
