### ISSUE TITLE
City Lights Icon Theme for VS Code

### ISSUE THREAD

**Issue by coderdiaz** [Yummygum/city-lights-syntax-vsc#17]
Are you working on City Lights Icon Theme for VS Code? if the answer is no... Can I work on this feature for VS Code?

Greetings 🎉

**Comment by noudadrichem** [comment]
Hi @coderdiaz,

That is a great idea, can you provide me your email address so I can compose up an email.

Sincerely,

**Comment by coderdiaz** [comment]
@noudadrichem Sure, coderdiaz[at]gmail[dot]com

**Comment by Yummygum** [comment]
We've send you an email.

You can fork this repo: https://github.com/Yummygum/city-lights-icons-vsc.git and start coding. 😊
