### ISSUE TITLE
[Color-issue] Certain properties hard to read

### ISSUE THREAD

**Issue by ALim95** [Yummygum/city-lights-syntax-vsc#19]
Certain properties are masked and cant be read when selected as seen in the gif below.

![2018-05-27_13-58-36](https://user-images.githubusercontent.com/31213216/40582961-8d1a2dc4-61b6-11e8-9371-80d2a00bc26f.gif)

**Comment by ALim95** [comment]
Hey there! The following is the code snippet:
![image](https://user-images.githubusercontent.com/31213216/40611466-fdbfafca-62a8-11e8-8158-1632ef7f8648.png)

**Comment by noudadrichem** [comment]
I fixed this in the next update.

**Comment by noudadrichem** [comment]
Next time please just copy → paste the code inside a ```code block``` Now I had to type the code to debug it. I think others will agree with me 😊 😝

**Comment by noudadrichem** [comment]
![image](https://user-images.githubusercontent.com/16288476/42168798-4b981dd4-7e12-11e8-9a2b-ad1b366e2100.png)
