### ISSUE TITLE
C# too blue, distinction can be hard.

### ISSUE THREAD

**Issue by HeercoGrond** [Yummygum/city-lights-syntax-vsc#2]
![image](https://user-images.githubusercontent.com/21168987/32432570-5abe3596-c2d8-11e7-9c4e-c7a16d428f72.png)

In the above image, you can see that most of the base definitions are very much in the same colorspace making it harder to distinguish elements from each other. Compare this to monokai:

![image](https://user-images.githubusercontent.com/21168987/32432654-a9d39a72-c2d8-11e7-9990-5e41810d30d4.png)

My suggestion, doesn't have to be very drastic, but some text styling (italicizing and underlining) could help a long way with making it more distinctive and better to use.

Especially when looking at variable definitions (private static _Class_ variableName = new _Class_(someInput) )

**Comment by noudadrichem** [comment]
Hi @HeercoGrond,

You are right, C# is not a language we specifically optimized, we'll add this to our to do list.

Thanks for using City Lights. 😊
