### ISSUE TITLE
[Color-issue] Inconsistent colors in Ruby

### ISSUE THREAD

**Issue by bradykeeling** [Yummygum/city-lights-syntax-vsc#21]
The syntax highlighting is strange for less than statements in Ruby.

Also, the variable highlighting is different between VS Code and Atom.

In VS Code:
![screen shot 2018-05-31 at 3 14 05 pm](https://user-images.githubusercontent.com/3791996/40805870-4b4103dc-64e5-11e8-9400-57627c6da932.png)

Here's the correct highlighting in Atom:
![screen shot 2018-05-31 at 3 14 55 pm](https://user-images.githubusercontent.com/3791996/40805901-65f0b8ee-64e5-11e8-8329-39c5ccfd8c78.png)

**Comment by noudadrichem** [comment]
Hi @bradykeeling Thank you for noticing this issue, this is due Atom being much more flexible targeting specific element inside the DOM. VSCode handles this differently as far as my knowledge goes. Feel free to upload a PR. 😊
