### ISSUE TITLE
Autocomplete pop selection is hard to read

### ISSUE THREAD

**Issue by ashtonlance** [Yummygum/city-lights-syntax-vsc#22]
I often have a hard time telling which item is selected in the autocomplete popup. Any chance it could be changed to a lighter color?

![city-light-autocomplete](https://user-images.githubusercontent.com/13652692/41720228-62af7c0a-7530-11e8-9892-c959a88995cd.png)

**Comment by noudadrichem** [comment]
@ashtonlance → Fixed in the next update. 😊 
![image](https://user-images.githubusercontent.com/16288476/42168924-96f16e0c-7e12-11e8-89af-fc9d1866e78e.png)

Let me know if other weird things occur!
