### ISSUE TITLE
The color of code blocks in extensions' description are same as its background

### ISSUE THREAD

**Issue by lastingman** [Yummygum/city-lights-syntax-vsc#23]
The color of code blocks in extensions' description are same as its background

![image](https://user-images.githubusercontent.com/10057502/42010013-65549be0-7abf-11e8-8d85-4d0ede2021a8.png)
![image](https://user-images.githubusercontent.com/10057502/42010023-6dc0b8f4-7abf-11e8-8838-9968e48db17a.png)

**Comment by noudadrichem** [comment]
Oeeh, bad one...! Fixed in the next update.
