### ISSUE TITLE
Comments are hard to read

### ISSUE THREAD

**Issue by Merrit** [Yummygum/city-lights-syntax-vsc#24]
Loving the colors in this theme, but I often find myself squinting to read the comments since they nearly blend into the background. Maybe we could turn up the brightness on them a little?

**Comment by noudadrichem** [comment]
Closed due design choices, you can use upper snippet to change colors.

**Comment by domenukk** [comment]
```json
"editor.tokenColorCustomizations": {
  "comments": "#b7c5d3"
},
```
really helps. Thank you!
