### ISSUE TITLE
Intellisense dropdown menu color

### ISSUE THREAD

**Issue by jokeefe1** [Yummygum/city-lights-syntax-vsc#25]
The intellisense drop-down menu (selected option) color is almost indistinguishable from the dark background of the box.  Obviously I like the dark color scheme but can the selected item color be just a slight bit lighter so I can more easily distinguish which option I am selecting?

**Comment by noudadrichem** [comment]
Hi @jokeefe1,

Can you provide a screenshot of what you mean? I'm not using VSCode myself but I do like to give you proper help.

**Comment by noudadrichem** [comment]
@jokeefe1 ❓😊
