### ISSUE TITLE
Beautiful theme, but git number/counter

### ISSUE THREAD

**Issue by locohost** [Yummygum/city-lights-syntax-vsc#28]
Love, love, love this theme. Thank you my friend! Only issue is Git number/counter unreadable. How do I change that?

**Comment by noudadrichem** [comment]
Hi @locohost ,

Glad you like the theme! Do you mind providing a screenshot of what you mean?

**Comment by locohost** [comment]
Definitely! Thanks for the fast reply :-)

![image](https://user-images.githubusercontent.com/132458/44920705-a8539f00-ad0e-11e8-96df-66289d8810d5.png)

**Comment by locohost** [comment]
I guess "unreadable" is not a good description. But the black/dark-gray are so close, it's just barely readable.

**Comment by noudadrichem** [comment]
Ah I see! This should be blue as it previously was. I'll update this soon. I'll keep you up to date!

**Comment by locohost** [comment]
Thank you! :-)

**Comment by mittalyashu** [comment]
Here's another screenshot.

VS Code updates

![image](https://user-images.githubusercontent.com/29014463/45545628-8262ea00-b838-11e8-9df0-a1e65ed094df.png)

Git Status

![code - insiders_2018-09-14_16-08-50](https://user-images.githubusercontent.com/29014463/45545662-9ad30480-b838-11e8-8e26-0a017416da56.png)

**Comment by noudadrichem** [comment]
This is fixed in version 1.0.7

![image](https://user-images.githubusercontent.com/16288476/45548253-f1821380-b823-11e8-9706-65656ea048b8.png)
