### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by mittalyashu** [Yummygum/city-lights-syntax-vsc#29]
Can you add a separate LICENSE file?

**Comment by noudadrichem** [comment]
It's possible. May I ask where do you need it for?

**Comment by mittalyashu** [comment]
It's just that if you can create a seperate LICENSE file, it will directly show up here:

![image](https://user-images.githubusercontent.com/29014463/45584223-6705e680-b8ed-11e8-92d0-6e49546a1b7f.png)

and it will be visible to everyone more easily.
