### ISSUE TITLE
Install with vscode insiders build

### ISSUE THREAD

**Issue by dandevri** [Yummygum/city-lights-syntax-vsc#3]
The path to vscode extensions on the *insiders build* is different than the *normal* path.

`git clone https://github.com/Yummygum/city-lights-syntax-vsc.git ~/.vscode-insiders/extensions/city-lights-theme`

Maybe it's nice to make a distinction in the readme.

**Comment by dandevri** [comment]
Made a pull request for this. #4

**Comment by noudadrichem** [comment]
Hi @dandevri ,

This is something we'll edit soon, the path is also different on Windows/Ubuntu. I'll let you know.
