### ISSUE TITLE
Status bar color when running debug

### ISSUE THREAD

**Issue by Superpencil** [Yummygum/city-lights-syntax-vsc#37]
Gray text on gray background when running debug server for rails:
<img width="960" alt="screen shot 2018-11-21 at 15 59 11" src="https://user-images.githubusercontent.com/3094044/48824046-69316900-eda6-11e8-980c-fc06e1ec28c4.png">

Orange in default dark:
<img width="960" alt="screen shot 2018-11-21 at 16 00 02" src="https://user-images.githubusercontent.com/3094044/48824074-88c89180-eda6-11e8-8c7c-aed91c25f87f.png">

**Comment by noudadrichem** [comment]
Good one, can you check the TM Scope for me?

**Comment by Superpencil** [comment]
@noudadrichem couldn't figure out how to check TM Scope on the statusbar with the built-in tool, but I found this online and it works:
```
"workbench.colorCustomizations": 
{
    "statusBar.background": "#21252B",
    "statusBar.foreground": "#9DA5B3",
    "statusBar.debuggingBackground": "#6c2022",
    "statusBar.debuggingForeground": "#9DA5B3",
    "statusBar.noFolderBackground": "#21252B",
    "statusBar.noFolderForeground": "#9DA5B3",
    "statusBarItem.activeBackground": "#598DEFD8",
    "statusBarItem.hoverBackground": "#598DEF59",
    "statusBarItem.prominentBackground": "#21252B",
    "statusBarItem.prominentHoverBackground": "#598DEF59",
}
```

It's `statusBar.debuggingBackground` and `statusBar.debuggingForeground` I think ✌🏻

**Comment by noudadrichem** [comment]
Nice scope of the situation! thanks

**Comment by noudadrichem** [comment]
This will be updated in version: 10.12
