### ISSUE TITLE
Snippet comments hard to see

### ISSUE THREAD

**Issue by tj** [Yummygum/city-lights-syntax-vsc#38]
Awesome theme! I noticed that snippet comments look a little tricky to read, but not a big deal

<img width="276" alt="screen shot 2019-01-24 at 2 38 04 pm" src="https://user-images.githubusercontent.com/25254/51685181-ace26200-1fe5-11e9-9202-9baa9ffb220b.png">

**Comment by noudadrichem** [comment]
Hi @tj,

That's something we've addressed earlier see #24. You can edit this inside your personal settings if you're not liking the comment brightness. Issue #24 also includes City Lights schemed colors
