### ISSUE TITLE
Main Font Color

### ISSUE THREAD

**Issue by foundationalnotes** [Yummygum/city-lights-syntax-vsc#43]
Hello - 

I'm new to Visual Studio Code. Can you point me to the correct way to change the main font white? For clarification please see this photo:

![font](https://user-images.githubusercontent.com/36466636/53125960-1bef9f80-352d-11e9-8bf7-1f7725141a3f.png)

In ST3 I simply looked at the scope and made the changes in the theme file. I tried using a scope extension in VSC but it did not work well for me. 

Thanks for your help.

**Comment by noudadrichem** [comment]
So you fixed it?
