### ISSUE TITLE
Border around enabled input inline options

### ISSUE THREAD

**Issue by gdlx** [Yummygum/city-lights-syntax-vsc#44]
I have a hard time knowing if an input field inline option is enabled or not.

Here's an example from the search tab:
![image](https://user-images.githubusercontent.com/1533042/53244186-66e2f180-36aa-11e9-86ec-efcd3eb07e69.png)

Default VSCode theme adds a border around enabled options, which makes very clear which ones are enabled or not:
![image](https://user-images.githubusercontent.com/1533042/53244262-a14c8e80-36aa-11e9-80ff-cf210309eced.png)

Could you add this kind of border in CityLights to avoid confusion ?

Thanks !

**Comment by gdlx** [comment]
Also note that hover color being the same than enabled color, you have to remove the mouse from the icon to actually see the difference when enabling/disabling an option.

The original theme border changes at click, nevermind the mouse is over the icon or not.

**Comment by noudadrichem** [comment]
I'll check up on this. Thanks for the heads up!
