### ISSUE TITLE
comment style changes are intrusive

### ISSUE THREAD

**Issue by jordanbrauer** [Yummygum/city-lights-syntax-vsc#50]
Hello! I notice that my VSCode theme updated and ~my PHP~ file comments have been rendered in italics without the colour ([see README screenshot](https://github.com/Yummygum/city-lights-syntax-vsc#city-lights-color-theme) for expected comment style), ever since. Here is a screenshot of what it looks like now (line 3):

![image](https://user-images.githubusercontent.com/18744334/59879604-b1326180-9370-11e9-9427-83b0b05bf0de.png)

I am also certain that the docblocks and comments should not italicized.

![image](https://user-images.githubusercontent.com/18744334/59880261-3cf8bd80-9372-11e9-9e39-84fe04db627e.png)

~Could this been caused by any of the recent commits made yesterday (June 19th, 2019)? If you'd like a hand investigating I can take a look, because~ I believe it was changed in commit dda666c. This change is quite the eye sore with the other syntax being highlighted with such beautiful colours...

**Comment by noudadrichem** [comment]
This is indeed an issue that appeared with the last update. Thanks @IanRohde for picking this up so fast!
