### ISSUE TITLE
Make git ignored files/folder a different(lighter) color than other files/folders

### ISSUE THREAD

**Issue by fidalgodev** [Yummygum/city-lights-syntax-vsc#55]
Git ignored files/folders are the same color as all of the other files/folders. Would suggest to make them a lot more lighter so it's easier to see they are git ignored.

**Comment by noudadrichem** [comment]
Hee @fidalgodev,

This is a very good idea as I know this is possible in Atom. But I can't seem to find an option to do this within VSCode regular settings. If you have an option let me know!
