### ISSUE TITLE
Please, update the theme, show us some &hearts.

### ISSUE THREAD

**Issue by SukhboldAltangerel** [Yummygum/city-lights-syntax-vsc#59]
![Capture](https://user-images.githubusercontent.com/16746009/73132132-a69c2100-4051-11ea-8022-5de486c2d80a.PNG)

Literally unusable!

Been using City Lights theme as long as I got into coding and had VS Code editor. And here I can't help myself but want more out of it. Please, give us a more sophisticated, and aesthetically pleasing new version of it, thank you. *Request.

**Comment by noudadrichem** [comment]
Hi, 

Thank you for using City Lights! Do you have any more information on why it's literally 'unusable' to you? The screenshot provided is a bit vague to me in this context. What do you want more out of it? 
If you want a new version with different colors etc. I would suggest just searching for another theme. City Lights has it's own color pallet.
I do understand that bugs are there and I would suggest just to make issues for bugs you encounter, I'm happy to fix these bugs! 

Kind Regards.

**Comment by SukhboldAltangerel** [comment]
editorGroup.background is deprecated, that's all as far as I know. Thanks.
