### ISSUE TITLE
JSX syntax

### ISSUE THREAD

**Issue by pvpshoot** [Yummygum/city-lights-syntax-vsc#6]
JSX syntax to hard to read
https://monosnap.com/file/Emc4l2DXIZzmgZqpQAHRNasN0FA5DC

**Comment by noudadrichem** [comment]
Hi @pvpshoot ,

What package for JSX syntax highlighting are you using?

I'm currently using react (https://atom.io/packages/react) (`apm install react`)
which has a different look than you have.
see:
http://jmp.sh/ysfpQAR

**Comment by pvpshoot** [comment]
we use https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

Michael Sinyakov (Fron-end developer)

**Comment by noudadrichem** [comment]
hi @pvpshoot ,

Are you using a specific package?
My JSX highlighting is the normal JS and HTML syntax combined. I use the normal javascript syntax highlighting

**Comment by pvpshoot** [comment]
Both of them highlights components like a props 

Michael Sinyakov (Fron-end developer)

**Comment by noudadrichem** [comment]
I'm not able to reconstruct this issue on my end, it might be a combination of plugins?
