### ISSUE TITLE
Debug controls unreadable in latest version of VSC

### ISSUE THREAD

**Issue by nermolov** [Yummygum/city-lights-syntax-vsc#62]
![image](https://user-images.githubusercontent.com/6175137/77917726-e6a59d00-7268-11ea-94ed-40cc8b361ae6.png)

**Comment by noudadrichem** [comment]
Came across this aswel. I'm gonna fix this!

**Comment by frani** [comment]
I have same problem when I comparing different on GIT

<img width="1221" alt="Captura de Pantalla 2020-03-30 a la(s) 13 11 38" src="https://user-images.githubusercontent.com/9354091/77935652-1b751c80-7288-11ea-8f83-c46c899fe1ad.png">

**Comment by nick-janda** [comment]
Yes, don't forget the git diffs, they hard to read with the last change!

**Comment by jordanbrauer** [comment]
Not only the git diffs, but the hover tooltips too!

![image](https://user-images.githubusercontent.com/18744334/78052266-7d935780-7344-11ea-9743-f84ec76a764a.png)

**Comment by noudadrichem** [comment]
Oh shiet. Lot has broken. 😂 I'm very sorry folks. I'm gonna fix this all asap!

**Comment by jeffswt** [comment]
![image](https://user-images.githubusercontent.com/18145331/78112931-82820500-7431-11ea-95b0-1f57033cdcd0.png)

And bracket matches too (facepalm)

**Comment by noudadrichem** [comment]
I though I only edited font colors...

**Comment by noudadrichem** [comment]
This is fixed in `1.1.8`. Please update. Sorry for the disruption.

**Comment by noudadrichem** [comment]
Also thanks for reporting this!

**Comment by noudadrichem** [comment]
If you folks need any other City Ligths related themes you can visit my gist page:https://gist.github.com/noudadrichem/

**Comment by jordanbrauer** [comment]
> If you folks need any other City Ligths related themes you can visit my gist page:https://gist.github.com/noudadrichem/

Haha that is awesome, thanks. I already use the mac terminal one on all my machines, but didn't know you had a Vim one too!
