### ISSUE TITLE
Terminal white texts too bright

### ISSUE THREAD

**Issue by vespa-r** [Yummygum/city-lights-syntax-vsc#67]
I like the colors of this theme, but one issue is the white text on terminal is too bright. The contrast is too high comparing with other colors of the theme. It would be great to dim it a little.

**Comment by locohost** [comment]
What kind of file are you looking at? What extension?

**Comment by vespa-r** [comment]
.js and .py

**Comment by fhbenatti** [comment]
Agreeded, I usually override the vscode setting `"terminal.foreground"` with #B7C5D3

**Comment by noudadrichem** [comment]
It's indeed possible to customize it to a colour of choise.

**Comment by fhbenatti** [comment]
> Agreeded, I usually override the vscode setting `"terminal.foreground"` with #B7C5D3



> It's indeed possible to customize it to a colour of choise.

The problem of this approach is to fixed this color to all themes. If you change to another theme it still keep this color for terminal.
