### ISSUE TITLE
Publish to VSCode store

### ISSUE THREAD

**Issue by sallar** [Yummygum/city-lights-syntax-vsc#7]
Hi, 

Is there a reason that you haven't published this to the vscode store? Many people like installing extensions and themes from there and cloning is not a good solution IMO (lack of auth updates, etc)

**Comment by edwinramirez** [comment]
Have to agree with @sallar (sorry for posting and sending unwanted notifications). I, personally, don't like filling my computer with Git repos and having to check for updates manually. If this theme gets published to the VSC store then updates are notified automatically.

**Comment by noudadrichem** [comment]
Hi!

Glad you guys like the theme! We'll look into this matter. 😊

**Comment by danielwaltz** [comment]
@noudadrichem Any updates to share? I'd love to see the VScode version get more lovin'. If you accept pull requests I can help contribute too.

**Comment by noudadrichem** [comment]
You can always make pull requests! 😊

**Comment by noudadrichem** [comment]
Hi guys, @sallar @edwinramirez @danielwaltz 

I published the theme to the VSCode marketplace:
https://marketplace.visualstudio.com/items?itemName=Yummygum.city-lights-theme
