### ISSUE TITLE
Differentiate object keys

### ISSUE THREAD

**Issue by danielwaltz** [Yummygum/city-lights-syntax-vsc#8]
Right now javascript objects are kinda hard to read as the whole block is the same color. Could this aspect be improved?

![image](https://user-images.githubusercontent.com/27220297/32842932-7395b8ee-c9ec-11e7-9c94-ed626fe0f1a1.png)

I am in love with this color theme tho!

**Comment by noudadrichem** [comment]
hi @danielwaltz,

Thank you for reporting this issue and i'm very glad you like the theme! 
I'll take a look at this and keep  you posted via this issue!

**Comment by noudadrichem** [comment]
Hi @danielwaltz ,

I'm currently trying to fix this but, VSCode handles this as default behavior. I took a look at other themes and how they approach this issue, but wasn't able to find any good solutions.
